# .streamlit/secrets.toml

supabase_url = "https://qddcnltimjelngjjdgma.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkZGNubHRpbWplbG5nampkZ21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTEzMTAyMjcsImV4cCI6MjAwNjg4NjIyN30.VqbGMR8nKYwcPCHvLNtvZUsp3_yALdTc8AT5AvbzMss"
